<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link   rel="stylesheet" href="/css/home.css" type="text/css" />
        <script type="text/javascript">
            var currentUser = <% userid %>
        </script>
        <script src="/js/soundlib.js"></script>
        <script src="/js/home.js"></script>
    </head>
    <body>
        <h1><% banner %></h1>

        <div class="user">
            <span>Hello <span id ="name" ></span>! (<span id ="email" ></span>)</span>
        </div>
        <div class="collection">
            <span>Ma collection </span>
            <div id="collection" >
                <% collection %>
            </div>
        </div>
        <div class="playlist">
            <span>Ma playlist </span>
            <div id="playlist" >

            </div>
        </div>
    </body>
</html>
