<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="/js/soundlib.js"></script>
        <script src="/js/home.js"></script>
    </head>
    <body>
        <div>TODO write content</div>
        <p><% text %></p>
        
        <span>My favorites playlist contains : </span>
        
        <div id="playlist" >
            
        </div>
        
        <button id="favorites" value="Favorites" onclick="Home.getUserFavorites(1513)" >Favorites</button>
        
    </body>
</html>
